### ISSUE TITLE
skipthoughts

### ISSUE THREAD

**Issue by INGSLEY** [xiaoyuan1996/GaLR#4]
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    main(update_options)
  File "train.py", line 60, in main
    data_parallel=False)
  File "/mnt/home/y22301054/GaLR-main/layers/GaLR.py", line 136, in factory
    model = BaseModel(opt, vocab_words)
  File "/mnt/home/y22301054/GaLR-main/layers/GaLR.py", line 99, in __init__
    opt = opt
  File "/mnt/home/y22301054/GaLR-main/layers/GaLR_utils.py", line 325, in __init__
    self.seq2vec = seq2vec.factory(self.vocab_words, self.opt['seq2vec'], self.opt['seq2vec']['dropout'])
  File "/mnt/home/y22301054/GaLR-main/layers/seq2vec.py", line 21, in factory
    fixed_emb=opt['fixed_emb'])
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/skipthoughts/skipthoughts.py", line 269, in __init__
    super(BayesianUniSkip, self).__init__(dir_st, vocab, save, dropout, fixed_emb)
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/skipthoughts/skipthoughts.py", line 155, in __init__
    super(AbstractUniSkip, self).__init__(dir_st, vocab, save, dropout, fixed_emb)
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/skipthoughts/skipthoughts.py", line 34, in __init__
    self.embedding = self._load_embedding()
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/skipthoughts/skipthoughts.py", line 88, in _load_embedding
    parameters = self._load_emb_params()
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/skipthoughts/skipthoughts.py", line 61, in _load_emb_params
    params = numpy.load(path_params, encoding='latin1', allow_pickle=True) # to load from python2
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/numpy/lib/npyio.py", line 441, in load
    pickle_kwargs=pickle_kwargs)
  File "/mnt/home/y22301054/anaconda3/envs/GaLR/lib/python3.7/site-packages/numpy/lib/format.py", line 748, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

**Comment by INGSLEY** [comment]
Please, who can tell me how to solve this problem, thank you

**Comment by xiaoyuan1996** [comment]
Judging from the error report, it seems that the file is corrupted? How about you re-download the skipthoughts file and try?

**Comment by INGSLEY** [comment]
A new day, just reconfigure a virtual environment, the problem disappears.
